
// This file is auto generated by 'actionapi' lib

import useSdkFetch from "actionapi/lib/client/useFetcher"

export const getAllProducts = () => useSdkFetch('getAllProducts', 'GET', `/products/`, {} )
export const getProduct = ({name}) => useSdkFetch('getProduct', 'GET', `/products/name?name=${name ?? ""}`, {name} )
export const getUser = ({name}) => useSdkFetch('getUser', 'GET', `/users/${name}`, {name} )
export const getAllUsers = () => useSdkFetch('getAllUsers', 'GET', `/users/`, {} )
