
// This file is auto generated by 'actionapi' lib

import sdkFetch from "actionapi/lib/client/fetcher"

export const getAllProducts = () => sdkFetch('getAllProducts', 'GET', `/products/`, {} );
export const getProduct = ({name}) => sdkFetch('getProduct', 'GET', `/products/name?name=${name ?? ""}`, {name} );
export const getUser = ({name}) => sdkFetch('getUser', 'GET', `/users/${name}`, {name} );
export const addUser = ({name,age}) => sdkFetch('addUser', 'POST', `/users/`, {name,age} , {name,age});
export const getAllUsers = () => sdkFetch('getAllUsers', 'GET', `/users/`, {} );
