
// This file is auto generated by 'actionapi' lib

import sdkFetch, { setConfig } from "actionapi/lib/fetcher"

setConfig({ baseUrl: '/api' })

/**
  *
  * @type {import("actionapi/lib/type").SetSdkConfig} setSdkConfig
  * @returns void
  */
export const setSdkConfig = (globalconfig) => setConfig(globalconfig);

export const SDK = {

getAllProducts: () => sdkFetch('getAllProducts', 'GET', `/products/`, {} ),
getProduct: ({name}) => sdkFetch('getProduct', 'GET', `/products/name?name=${name || ""}`, {name} ),
getAllUsers: () => sdkFetch('getAllUsers', 'GET', `/users/`, {} ),
getUser: ({name}) => sdkFetch('getUser', 'GET', `/users/${name}`, {name} ),
addUser: ({name,age}) => sdkFetch('addUser', 'POST', `/users/`, {name,age} , {name,age}),

}