
//  This file is auto generated by 'actionapi' 


import sdkFetch, { settings, setConfig } from "actionapi/lib/fetcher"  
export const setSdkConfig = setConfig 
export const SDK = {

getAllProducts: () => sdkFetch(`${settings.config.baseUrl}/api/products/`, {method: 'GET' }).then((res) => res.json()),
/** 
 * @param input getProduct's inputs 
 * @param input.name */
getProduct: ({name}) => sdkFetch(`${settings.config.baseUrl}/api/products/name?name=${name || ""}`, {method: 'GET' }).then((res) => res.json()),
getAllUsers: () => sdkFetch(`${settings.config.baseUrl}/api/users/`, {method: 'GET' }).then((res) => res.json()),
/** 
 * @param input getUser's inputs 
 * @param input.name */
getUser: ({name}) => sdkFetch(`${settings.config.baseUrl}/api/users/${name}`, {method: 'GET' }).then((res) => res.json()),
/** 
 * @param input addUser's inputs 
 * @param input.name  * @param input.age */
addUser: ({name,age}) => sdkFetch(`${settings.config.baseUrl}/api/users/`, {method: 'POST' , body: {name,age}}).then((res) => res.json()),

}