
// This file is auto generated by 'actionapi' lib

import sdkFetch, { setConfig } from "actionapi/lib/fetcher"

import useSdkFetch from "actionapi/lib/useFetcher"

setConfig({ baseUrl: '/docs' })

/**
  *
  * @type {import("actionapi/lib/type").SetSdkConfig} setSdkConfig
  * @returns void
  */
export const setSdkConfig = (globalconfig) => setConfig(globalconfig);

export const SDK = {

getAllProducts: () => sdkFetch('getAllProducts', 'GET', `/products/`, {} ),
getProduct: ({name}) => sdkFetch('getProduct', 'GET', `/products/name?name=${name || ""}`, {name} ),
getAllUsers: () => sdkFetch('getAllUsers', 'GET', `/users/`, {} ),
getUser: ({name}) => sdkFetch('getUser', 'GET', `/users/${name}`, {name} ),
addUser: ({name,age}) => sdkFetch('addUser', 'POST', `/users/`, {name,age} , {name,age}),

}

export const useSdk = {

getAllProducts: () => useSdkFetch('getAllProducts', 'GET', `/products/`, {} ),
getProduct: ({name}) => useSdkFetch('getProduct', 'GET', `/products/name?name=${name || ""}`, {name} ),
getAllUsers: () => useSdkFetch('getAllUsers', 'GET', `/users/`, {} ),
getUser: ({name}) => useSdkFetch('getUser', 'GET', `/users/${name}`, {name} ),

}

export const ACTIONS = {

getAllProducts: 'getAllProducts',getProduct: 'getProduct',getAllUsers: 'getAllUsers',getUser: 'getUser',addUser: 'addUser',
}

