const RequestParameterType = require("../index");
const fs = require("fs");
const package = require("../package.json");

module.exports = (configs) => {
  const { root, apiFiles, prefix: appPrefix, path = process.cwd(), sdkFile = "sdk.gen.js" } = configs;

  let file = `\n//  This file is auto generated by '${package.name}' \n\n\n`;
  file += `import sdkFetch, { settings, setConfig } from "${package.name}/lib/fetcher"  \n`;

  file += "export const setSdkConfig = setConfig \n";

  file += "export const SDK = {\n\n";

  Object.keys(apiFiles)
    .sort()
    .forEach((prefix) =>
      apiFiles[prefix]
        .getRoutes()
        .sort((a, b) => (a.action < b.action ? -1 : 1))
        .forEach((route) => {
          let url = "${settings.config.baseUrl}" + `${appPrefix}${prefix}${route.path}`;

          const params = [];
          const query = [];
          const body = [];

          Object.entries(route.input || {}).forEach((entry) => {
            if (entry[1] === RequestParameterType.QUERY) query.push(entry[0]);
            else if (entry[1] === RequestParameterType.PARAM) params.push(entry[0]);
            else body.push(entry[0]);
          });

          if (query.length) url += "?";
          const queryString = query.map((k) => `${k}=${"${" + k + ' || ""}'}`).join("&");
          params.forEach((param) => (url = url.replace(`{${param}}`, `${"${" + param + "}"}`)));

          const actionInputs = [...params, ...query, ...body];
          const actionArgsStr = !query.length && !body.length && !params.length ? "" : `{${actionInputs.join(",")}}`;

          const actionInputsDocs = actionInputs.length
            ? `/** \n * @param input ${route.action.name}'s inputs \n${actionInputs.map((i) => ` * @param input.${i}`).join(" ")} */\n`
            : "";

          const bodyString = body.length ? `, body: {${body.join(",")}}` : "";
          file += actionInputsDocs;
          file += `${route.action.name}: (${actionArgsStr}) => sdkFetch(\`${url}${queryString}\`, {method: '${route.method}' ${bodyString}}).then((res) => res.json()),\n`;
        })
    );

  file += "\n}";
  let currentFile = "";
  try {
    currentFile = fs.readFileSync(`${path}/${sdkFile}`) + "";
  } catch (e) {
  } finally {
    if (file !== currentFile) {
      fs.writeFileSync(`${path}/${sdkFile}`, file);
    }
  }
};
