
// This file is auto generated by 'actionapi' lib

import sdkFetch, { setConfig } from "actionapi/lib/fetcher"

import useSdkFetch from "actionapi/lib/useFetcher"

/**
  *
  * @type {import("actionapi/lib/type").SetSdkConfig} setSdkConfig
  * @returns void
  */
export const setSdkConfig = (globalconfig) => setConfig(globalconfig);

export const SDK = {


}

export const useSdk = {


}

export const ACTIONS = {


}

