
// This file is auto generated by 'actionapi' lib

import sdkFetch, { setConfig } from "actionapi/lib/fetcher"

import useSdkFetch from "actionapi/lib/useFetcher"

setConfig({ baseUrl: '/docs' })

/**
  *
  * @type {import("actionapi/lib/type").SetSdkConfig} setSdkConfig
  * @returns void
  */
export const setSdkConfig = (globalconfig) => setConfig(globalconfig);

export const SDK = {

testAction: () => sdkFetch('testAction', 'GET', `/api/test`, {} ),

}

export const useSdk = {

testAction: () => useSdkFetch('testAction', 'GET', `/api/test`, {} ),

}

export const ACTIONS = {

testAction: 'testAction',
}

