name: publish to npm registry
run-name: ${{ github.actor }} is publishing to npm
on:
  push:
    branches:
      - "main"
    path:
      - "package.json"
jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - uses: mikeal/merge-release@v4.3.0
